### PR TITLE
sound preview

### PR DESCRIPTION
**Pull request by clydeshaffer**
- embed the emulator wasm build
- box it off like a mail slot to look like a progress bar for the playing sound
- add "Preview" button that copies the sound data into the ROM buffer then simulates an "A" press (rip that one mario64 run)
- gametank emulator and its canvas are initialized outside the scope of react but then hijacked by react's DOM

### CODE REVIEW

**Comment by nickgirardo** [comment]
I'm pretty sure that the emulator is eating all the keyboard input

**Comment by nickgirardo** [comment]
Ok, so as my earlier message stated the emulator was eating all keyboard input.  There were a few hacky ways I was able to disable this, but I was struggling to find something that didn't require manually editing the machine output `emulator.js`.  (My message on discord about the wasm emulator build was bc I was thinking about making a version of that which didn't poll for events lol).  There were some docs about modularizing with a `-sMODULARIZE` arg to emscripten, but manually modularizing seemed like a massive pain tbh. Eventually I realized that I could super easily encapsulate it by just sticking it in an `<iframe>`!  This is slightly janky but actually works pretty well.  To make matters a bit nicer, it's actually pretty easy to call into a child `<iframe>` so the `previewSound` code is quite simple.
I also fixed up a few vite issues in your pr. I've moved `emulator.js` and `emulator.wasm` from within `src/` to `public/`, `src/` is for files bundled by vite.

**Comment by nickgirardo** [comment]
I'd appreciate if you tested this out to make sure it's still mostly working.  It appears as though you must first click the gte to load it.  I'm not 100% sure if this is from the emulator or if it's a browser policy thing (e.g. you can't play audio without first having some user interaction).

**Comment by nickgirardo** [comment]
Also, it'd be nice to add some notes in the readme about how the `emulator.js` and `emulator.wasm` are build products of your emulator repo. Is `roms/sfx.gtr` a custom rom you built and compiled into the emulator at build time? It'd be nice to have a link to that if possible.

**Comment by clydeshaffer** [comment]
On the emulator side I'll probably make a dedicated branch for the audio preview version, like the sfx.gtr that was bundled in.

Having to click on the emulator might be a product of it being in an iframe. Normally you do need to click somewhere but anywhere on the same page should count and it wouldn't care whether you click on the canvas. Putting it in an iframe might be enough separation that it makes you click in the guest page.

**Comment by clydeshaffer** [comment]
The iframe also has big clunky scroll bars. Between that and having to click on it to preview, could the iframe be avoided and still keep keyboard from getting swallowed?

**Comment by clydeshaffer** [comment]
For modularizing the emulator, two things that it needs to overcome are that everything in emulator.js should probably happen just once per page load. I attempted to get it to run from the GTEmulator.tsx component but it was always getting run three times for some reason.

The other obstacle is that it needs to be able to attach to a canvas element when it runs, which is why I ended up making a canvas element that gets created before anything else so it's available to the emulator.js code.

**Comment by clydeshaffer** [comment]
The emulator version for this is at https://github.com/clydeshaffer/GameTankEmulator/tree/sfx_preview
and built with
```
 make OS=wasm ROMFILE=roms/sfx.gtr WEB_SHELL=shell.html EXTRA_OPTIONS='-D DISABLE_KEYBOARD_INPUT'
 ```
 
 The sfx.gtr rom is built on the util/sfx_tester branch of the gametank_sdk repo
 
 The DISABLE_KEYBOARD_INPUT macro is new and I'm checking to see if that can prevent swallowing the keyboard events.

**Comment by nickgirardo** [comment]
> The iframe also has big clunky scroll bars. Between that and having to click on it to preview, could the iframe be avoided and still keep keyboard from getting swallowed?

The scrollbars have been removed, unsure why they were only being shown on chrome and not ffx

**Pull request merged**
